// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64) && linux

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type meshAllocMetrics struct {
	_          structs.HostLayout
	TotalBytes uint64
	AllocCount uint64
}

type meshRequestInfo struct {
	_       structs.HostLayout
	StartNs uint64
	RouteId uint32
	Padding uint32
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	meshMapActiveRequests      = "active_requests"
	meshMapBackendPids         = "backend_pids"
	meshMapBlockedPids         = "blocked_pids"
	meshMapCpuSamples          = "cpu_samples"
	meshMapEvents              = "events"
	meshMapProfiledPids        = "profiled_pids"
	meshMapServiceMetrics      = "service_metrics"
	meshProgCheckConnect       = "check_connect"
	meshProgDoCpuSample        = "do_cpu_sample"
	meshProgTraceFinishRequest = "trace_finish_request"
	meshProgTraceHealthEntry   = "trace_health_entry"
	meshProgTraceMalloc        = "trace_malloc"
	meshProgTraceWorkEntry     = "trace_work_entry"
)

// loadMesh returns the embedded CollectionSpec for mesh.
func loadMesh() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_MeshBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load mesh: %w", err)
	}

	return spec, err
}

// loadMeshObjects loads mesh and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*meshObjects
//	*meshPrograms
//	*meshMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadMeshObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadMesh()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// meshSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type meshSpecs struct {
	meshProgramSpecs
	meshMapSpecs
	meshVariableSpecs
}

// meshProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type meshProgramSpecs struct {
	CheckConnect       *ebpf.ProgramSpec `ebpf:"check_connect"`
	DoCpuSample        *ebpf.ProgramSpec `ebpf:"do_cpu_sample"`
	TraceFinishRequest *ebpf.ProgramSpec `ebpf:"trace_finish_request"`
	TraceHealthEntry   *ebpf.ProgramSpec `ebpf:"trace_health_entry"`
	TraceMalloc        *ebpf.ProgramSpec `ebpf:"trace_malloc"`
	TraceWorkEntry     *ebpf.ProgramSpec `ebpf:"trace_work_entry"`
}

// meshMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type meshMapSpecs struct {
	ActiveRequests *ebpf.MapSpec `ebpf:"active_requests"`
	BackendPids    *ebpf.MapSpec `ebpf:"backend_pids"`
	BlockedPids    *ebpf.MapSpec `ebpf:"blocked_pids"`
	CpuSamples     *ebpf.MapSpec `ebpf:"cpu_samples"`
	Events         *ebpf.MapSpec `ebpf:"events"`
	ProfiledPids   *ebpf.MapSpec `ebpf:"profiled_pids"`
	ServiceMetrics *ebpf.MapSpec `ebpf:"service_metrics"`
}

// meshVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type meshVariableSpecs struct {
}

// meshObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadMeshObjects or ebpf.CollectionSpec.LoadAndAssign.
type meshObjects struct {
	meshPrograms
	meshMaps
	meshVariables
}

func (o *meshObjects) Close() error {
	return _MeshClose(
		&o.meshPrograms,
		&o.meshMaps,
	)
}

// meshMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadMeshObjects or ebpf.CollectionSpec.LoadAndAssign.
type meshMaps struct {
	ActiveRequests *ebpf.Map `ebpf:"active_requests"`
	BackendPids    *ebpf.Map `ebpf:"backend_pids"`
	BlockedPids    *ebpf.Map `ebpf:"blocked_pids"`
	CpuSamples     *ebpf.Map `ebpf:"cpu_samples"`
	Events         *ebpf.Map `ebpf:"events"`
	ProfiledPids   *ebpf.Map `ebpf:"profiled_pids"`
	ServiceMetrics *ebpf.Map `ebpf:"service_metrics"`
}

func (m *meshMaps) Close() error {
	return _MeshClose(
		m.ActiveRequests,
		m.BackendPids,
		m.BlockedPids,
		m.CpuSamples,
		m.Events,
		m.ProfiledPids,
		m.ServiceMetrics,
	)
}

// meshVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadMeshObjects or ebpf.CollectionSpec.LoadAndAssign.
type meshVariables struct {
}

// meshPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadMeshObjects or ebpf.CollectionSpec.LoadAndAssign.
type meshPrograms struct {
	CheckConnect       *ebpf.Program `ebpf:"check_connect"`
	DoCpuSample        *ebpf.Program `ebpf:"do_cpu_sample"`
	TraceFinishRequest *ebpf.Program `ebpf:"trace_finish_request"`
	TraceHealthEntry   *ebpf.Program `ebpf:"trace_health_entry"`
	TraceMalloc        *ebpf.Program `ebpf:"trace_malloc"`
	TraceWorkEntry     *ebpf.Program `ebpf:"trace_work_entry"`
}

func (p *meshPrograms) Close() error {
	return _MeshClose(
		p.CheckConnect,
		p.DoCpuSample,
		p.TraceFinishRequest,
		p.TraceHealthEntry,
		p.TraceMalloc,
		p.TraceWorkEntry,
	)
}

func _MeshClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed mesh_x86_bpfel.o
var _MeshBytes []byte
