// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64 && linux

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type profilerAllocMetrics struct {
	_          structs.HostLayout
	TotalBytes uint64
	AllocCount uint64
}

type profilerStackAlloc struct {
	_     structs.HostLayout
	Bytes uint64
	Count uint64
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	profilerMapCpuSamples      = "cpu_samples"
	profilerMapCpuStackSamples = "cpu_stack_samples"
	profilerMapMemMetrics      = "mem_metrics"
	profilerMapStackAllocs     = "stack_allocs"
	profilerMapStackTraces     = "stack_traces"
	profilerProgDoCpuSample    = "do_cpu_sample"
	profilerProgTraceMalloc    = "trace_malloc"
	profilerVarTargetPid       = "target_pid"
)

// loadProfiler returns the embedded CollectionSpec for profiler.
func loadProfiler() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ProfilerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load profiler: %w", err)
	}

	return spec, err
}

// loadProfilerObjects loads profiler and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*profilerObjects
//	*profilerPrograms
//	*profilerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadProfilerObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadProfiler()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// profilerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type profilerSpecs struct {
	profilerProgramSpecs
	profilerMapSpecs
	profilerVariableSpecs
}

// profilerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type profilerProgramSpecs struct {
	DoCpuSample *ebpf.ProgramSpec `ebpf:"do_cpu_sample"`
	TraceMalloc *ebpf.ProgramSpec `ebpf:"trace_malloc"`
}

// profilerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type profilerMapSpecs struct {
	CpuSamples      *ebpf.MapSpec `ebpf:"cpu_samples"`
	CpuStackSamples *ebpf.MapSpec `ebpf:"cpu_stack_samples"`
	MemMetrics      *ebpf.MapSpec `ebpf:"mem_metrics"`
	StackAllocs     *ebpf.MapSpec `ebpf:"stack_allocs"`
	StackTraces     *ebpf.MapSpec `ebpf:"stack_traces"`
}

// profilerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type profilerVariableSpecs struct {
	TargetPid *ebpf.VariableSpec `ebpf:"target_pid"`
}

// profilerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadProfilerObjects or ebpf.CollectionSpec.LoadAndAssign.
type profilerObjects struct {
	profilerPrograms
	profilerMaps
	profilerVariables
}

func (o *profilerObjects) Close() error {
	return _ProfilerClose(
		&o.profilerPrograms,
		&o.profilerMaps,
	)
}

// profilerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadProfilerObjects or ebpf.CollectionSpec.LoadAndAssign.
type profilerMaps struct {
	CpuSamples      *ebpf.Map `ebpf:"cpu_samples"`
	CpuStackSamples *ebpf.Map `ebpf:"cpu_stack_samples"`
	MemMetrics      *ebpf.Map `ebpf:"mem_metrics"`
	StackAllocs     *ebpf.Map `ebpf:"stack_allocs"`
	StackTraces     *ebpf.Map `ebpf:"stack_traces"`
}

func (m *profilerMaps) Close() error {
	return _ProfilerClose(
		m.CpuSamples,
		m.CpuStackSamples,
		m.MemMetrics,
		m.StackAllocs,
		m.StackTraces,
	)
}

// profilerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadProfilerObjects or ebpf.CollectionSpec.LoadAndAssign.
type profilerVariables struct {
	TargetPid *ebpf.Variable `ebpf:"target_pid"`
}

// profilerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadProfilerObjects or ebpf.CollectionSpec.LoadAndAssign.
type profilerPrograms struct {
	DoCpuSample *ebpf.Program `ebpf:"do_cpu_sample"`
	TraceMalloc *ebpf.Program `ebpf:"trace_malloc"`
}

func (p *profilerPrograms) Close() error {
	return _ProfilerClose(
		p.DoCpuSample,
		p.TraceMalloc,
	)
}

func _ProfilerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed profiler_arm64_bpfel.o
var _ProfilerBytes []byte
