//go:build linux

package main

import (
	"bytes"
	"encoding/binary"
	"errors"
	"fmt"
	"log/slog"
	"math/rand"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/cilium/ebpf/link"
	"github.com/cilium/ebpf/ringbuf"
	"github.com/cilium/ebpf/rlimit"
)

type spanEvent struct {
	RouteID    uint32
	Padding    uint32
	DurationNs uint64
	Timestamp  uint64
}

func main() {
	if len(os.Args) < 2 {
		slog.Error("Missing arguments", "usage", fmt.Sprintf("%s <path-to-target-binary>", os.Args[0]))
		os.Exit(1)
	}
	binaryPath := os.Args[1]

	// Remove resource limits for kernels <5.11.
	if err := rlimit.RemoveMemlock(); err != nil {
		slog.Error("Failed to remove memlock limit", "error", err)
		os.Exit(1)
	}

	// Load eBPF programs.
	var objs tracerObjects
	if err := loadTracerObjects(&objs, nil); err != nil {
		slog.Error("Failed to load eBPF objects", "error", err)
		os.Exit(1)
	}
	defer objs.Close()

	// Open the target executable.
	ex, err := link.OpenExecutable(binaryPath)
	if err != nil {
		slog.Error("Failed to open target executable", "path", binaryPath, "error", err)
		os.Exit(1)
	}

	// Attach Uprobes.
	hEntry, err := ex.Uprobe("main.handleHealth", objs.TraceHealthEntry, nil)
	if err != nil {
		slog.Error("Failed to attach handleHealth entry uprobe", "error", err)
		os.Exit(1)
	}
	defer hEntry.Close()

	wEntry, err := ex.Uprobe("main.handleWork", objs.TraceWorkEntry, nil)
	if err != nil {
		slog.Error("Failed to attach handleWork entry uprobe", "error", err)
		os.Exit(1)
	}
	defer wEntry.Close()

	fRequest, err := ex.Uprobe("net/http.(*response).finishRequest", objs.TraceFinishRequest, nil)
	if err != nil {
		slog.Error("Failed to attach finishRequest uprobe", "error", err)
		os.Exit(1)
	}
	defer fRequest.Close()

	slog.Info("eBPF Auto-Instrumentation (Uprobes only) attached successfully", "target", binaryPath)

	// Read events from Ring Buffer.
	rd, err := ringbuf.NewReader(objs.Events)
	if err != nil {
		slog.Error("Failed to create ring buffer reader", "error", err)
		os.Exit(1)
	}
	defer rd.Close()

	stop := make(chan os.Signal, 1)
	signal.Notify(stop, os.Interrupt, syscall.SIGTERM)

	go func() {
		slog.Info("Tracer background loop listening for events...")
		var event spanEvent
		for {
			record, err := rd.Read()
			if err != nil {
				if errors.Is(err, ringbuf.ErrClosed) {
					return
				}
				slog.Error("Failed reading from ring buffer", "error", err)
				continue
			}

			if err := binary.Read(bytes.NewBuffer(record.RawSample), binary.LittleEndian, &event); err != nil {
				slog.Error("Failed parsing event record", "error", err)
				continue
			}

			printSpan(&event)
		}
	}()

	sig := <-stop
	slog.Info("Tracer shutting down gracefully", "signal", sig.String())
}

func routeIDToName(id uint32) string {
	switch id {
	case 1:
		return "/health"
	case 2:
		return "/api/work"
	default:
		return "/unknown"
	}
}

func printSpan(e *spanEvent) {
	// Since we are auto-instrumenting, we simulate TraceID/SpanID generation in the tracer
	traceID := fmt.Sprintf("%016x", rand.Uint64())
	spanID := fmt.Sprintf("%016x", rand.Uint64())
	routeName := routeIDToName(e.RouteID)
	duration := time.Duration(e.DurationNs)

	fmt.Println()
	fmt.Println("----------------- AUTO-INSTRUMENTED OpenTelemetry Span -----------------")
	fmt.Printf("TraceID:      %s (Generated by eBPF Tracer)\n", traceID)
	fmt.Printf("SpanID:       %s (Generated by eBPF Tracer)\n", spanID)
	fmt.Printf("Name:         HTTP GET %s\n", routeName)
	fmt.Printf("Duration:     %s (Measured in Kernel Space via eBPF Uprobes)\n", duration)
	fmt.Printf("Status:       OK\n")
	fmt.Printf("Timestamp:    %s\n", time.Now().Format(time.RFC3339Nano))
	fmt.Println("------------------------------------------------------------------------")
	fmt.Println()
}
