// Code generated by bpf2go; DO NOT EDIT.
//go:build (386 || amd64) && linux

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"
	"structs"

	"github.com/cilium/ebpf"
)

type tracerRequestInfo struct {
	_       structs.HostLayout
	StartNs uint64
	RouteId uint32
	Padding uint32
}

// Names of all BPF objects in the ELF.
//
// Used for safe lookups in a Collection or CollectionSpec.
const (
	tracerMapActiveRequests      = "active_requests"
	tracerMapEvents              = "events"
	tracerProgTraceFinishRequest = "trace_finish_request"
	tracerProgTraceHealthEntry   = "trace_health_entry"
	tracerProgTraceWorkEntry     = "trace_work_entry"
)

// loadTracer returns the embedded CollectionSpec for tracer.
func loadTracer() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_TracerBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load tracer: %w", err)
	}

	return spec, err
}

// loadTracerObjects loads tracer and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*tracerObjects
//	*tracerPrograms
//	*tracerMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadTracerObjects(obj any, opts *ebpf.CollectionOptions) error {
	spec, err := loadTracer()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// tracerSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tracerSpecs struct {
	tracerProgramSpecs
	tracerMapSpecs
	tracerVariableSpecs
}

// tracerProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tracerProgramSpecs struct {
	TraceFinishRequest *ebpf.ProgramSpec `ebpf:"trace_finish_request"`
	TraceHealthEntry   *ebpf.ProgramSpec `ebpf:"trace_health_entry"`
	TraceWorkEntry     *ebpf.ProgramSpec `ebpf:"trace_work_entry"`
}

// tracerMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tracerMapSpecs struct {
	ActiveRequests *ebpf.MapSpec `ebpf:"active_requests"`
	Events         *ebpf.MapSpec `ebpf:"events"`
}

// tracerVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type tracerVariableSpecs struct {
}

// tracerObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type tracerObjects struct {
	tracerPrograms
	tracerMaps
	tracerVariables
}

func (o *tracerObjects) Close() error {
	return _TracerClose(
		&o.tracerPrograms,
		&o.tracerMaps,
	)
}

// tracerMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type tracerMaps struct {
	ActiveRequests *ebpf.Map `ebpf:"active_requests"`
	Events         *ebpf.Map `ebpf:"events"`
}

func (m *tracerMaps) Close() error {
	return _TracerClose(
		m.ActiveRequests,
		m.Events,
	)
}

// tracerVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to loadTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type tracerVariables struct {
}

// tracerPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadTracerObjects or ebpf.CollectionSpec.LoadAndAssign.
type tracerPrograms struct {
	TraceFinishRequest *ebpf.Program `ebpf:"trace_finish_request"`
	TraceHealthEntry   *ebpf.Program `ebpf:"trace_health_entry"`
	TraceWorkEntry     *ebpf.Program `ebpf:"trace_work_entry"`
}

func (p *tracerPrograms) Close() error {
	return _TracerClose(
		p.TraceFinishRequest,
		p.TraceHealthEntry,
		p.TraceWorkEntry,
	)
}

func _TracerClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed tracer_x86_bpfel.o
var _TracerBytes []byte
