// Code generated by bpf2go; DO NOT EDIT.
//go:build arm64be || armbe || mips || mips64 || mips64p32 || ppc64 || s390 || s390x || sparc || sparc64

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// loadMesh returns the embedded CollectionSpec for mesh.
func loadMesh() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_MeshBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load mesh: %w", err)
	}

	return spec, err
}

// loadMeshObjects loads mesh and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*meshObjects
//	*meshPrograms
//	*meshMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func loadMeshObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := loadMesh()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// meshSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type meshSpecs struct {
	meshProgramSpecs
	meshMapSpecs
}

// meshSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type meshProgramSpecs struct {
	CheckConnect *ebpf.ProgramSpec `ebpf:"check_connect"`
}

// meshMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type meshMapSpecs struct {
	BlockedPids *ebpf.MapSpec `ebpf:"blocked_pids"`
	Events      *ebpf.MapSpec `ebpf:"events"`
}

// meshObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to loadMeshObjects or ebpf.CollectionSpec.LoadAndAssign.
type meshObjects struct {
	meshPrograms
	meshMaps
}

func (o *meshObjects) Close() error {
	return _MeshClose(
		&o.meshPrograms,
		&o.meshMaps,
	)
}

// meshMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to loadMeshObjects or ebpf.CollectionSpec.LoadAndAssign.
type meshMaps struct {
	BlockedPids *ebpf.Map `ebpf:"blocked_pids"`
	Events      *ebpf.Map `ebpf:"events"`
}

func (m *meshMaps) Close() error {
	return _MeshClose(
		m.BlockedPids,
		m.Events,
	)
}

// meshPrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to loadMeshObjects or ebpf.CollectionSpec.LoadAndAssign.
type meshPrograms struct {
	CheckConnect *ebpf.Program `ebpf:"check_connect"`
}

func (p *meshPrograms) Close() error {
	return _MeshClose(
		p.CheckConnect,
	)
}

func _MeshClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed mesh_bpfeb.o
var _MeshBytes []byte
